### ISSUE TITLE
Getting this error since this week's update

### ISSUE THREAD

**Issue by andrabela** [wardann/DungeonDocs#18]
3x DungeonDocs/Modules/Database.lua:244: attempt to index field 'movers' (a boolean value)
[string "@DungeonDocs/Modules/Database.lua"]:244: in function `DB_Init'
[string "@DungeonDocs/DungeonDocs.lua"]:19: in function <DungeonDocs/DungeonDocs.lua:9>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 modules = <table> {
 }
 defaultModuleState = true
 baseName = "DungeonDocs"
 db = <table> {
 }
 enabledState = true
 Dungeons = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "DungeonDocs"
 orderedModules = <table> {
 }
}
db = <table> {
 callbacks = <table> {
 }
 keys = <table> {
 }
 sv = <table> {
 }
 profile = <table> {
 }
 profiles = <table> {
 }
}
(*temporary) = false
(*temporary) = <table> {
 modules = <table> {
 }
 defaultModuleState = true
 baseName = "DungeonDocs"
 db = <table> {
 }
 enabledState = true
 Dungeons = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "DungeonDocs"
 orderedModules = <table> {
 }
}
(*temporary) = "attempt to index field 'movers' (a boolean value)"
DungeonDocs = <table> {
 modules = <table> {
 }
 defaultModuleState = true
 baseName = "DungeonDocs"
 db = <table> {
 }
 enabledState = true
 Dungeons = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "DungeonDocs"
 orderedModules = <table> {
 }
}

**Comment by wardann** [comment]
Hey @andrabela 👋 Thanks for checking out DungeonDocs! It's still early days for the addon

I just released a new build [v0.2.0-beta.2](https://github.com/wardann/DungeonDocs/releases/tag/v0.2.0-beta.2). Could you please give that a shot and let me know if the errors persist? This release contains a lot of performance improvements and bug fixes

**Comment by wardann** [comment]
Closing this for now as I haven't been able to reproduce with a more recent build. 

@andrabela feel free to reopen if you encounter this again
